USE [CalculadoraLoginDB];
GO
IF OBJECT_ID('dbo.Usuarios','U') IS NULL
BEGIN
 CREATE TABLE dbo.Usuarios(Id INT IDENTITY(1,1) PRIMARY KEY,Nombre NVARCHAR(100) NOT NULL,Correo NVARCHAR(150) NOT NULL UNIQUE,Password NVARCHAR(100) NOT NULL);
END
GO
CREATE OR ALTER PROCEDURE dbo.sp_Usuario_Login @Correo NVARCHAR(150),@Password NVARCHAR(100) AS BEGIN SET NOCOUNT ON;SELECT COUNT(1) FROM dbo.Usuarios WHERE Correo=@Correo AND Password=@Password;END
GO
CREATE OR ALTER PROCEDURE dbo.sp_Usuario_Registrar @Nombre NVARCHAR(100),@Correo NVARCHAR(150),@Password NVARCHAR(100) AS BEGIN SET NOCOUNT ON;IF EXISTS(SELECT 1 FROM dbo.Usuarios WHERE Correo=@Correo) BEGIN SELECT 0;RETURN;END INSERT dbo.Usuarios(Nombre,Correo,Password) VALUES(@Nombre,@Correo,@Password);SELECT 1;END
GO
